BOT-3: Рефакторинг и бизнес-доработки
Azat-Bilalov/event-automation pull request #3
Opened 2024-11-30 23:32 UTC by Azat-Bilalov

2024-11-30 23:33 UTC, Azat-Bilalov commented on bot/handlers/handlers.go
> +var UserMessages = make(map[int64][]string)
вот это прям не ок, нужно определиться, как будем хранить скоуп сообщений

2024-12-04 16:06 UTC, Vanv1k requested changes

2024-12-04 16:06 UTC, Vanv1k commented on bot/main.go
> +	state := handlers.NewUserProcessingState()
Создание UserProcessingState через пакет handlers как будто не очень хорошо. Возможно, стоит вынести в отдельный пакет эту структуру и логику работы с ней

2024-12-04 16:06 UTC, Vanv1k commented on bot/handlers/collector.go
> +}
Думаю стоит вынести эту логику в отдельный пакет, какой-нибудь state

2024-12-04 16:06 UTC, Vanv1k commented on bot/handlers/collector.go
> +	}()
по-хорошему я думаю тут стоит прокинуть в функцию message как параметр, потому что иначе тут могут возникнуть ошибки с переписыванием message до этого снаружи в функции. Хоть тут и будет, как я понял, вызываться функция отдельно для каждой пачки пересланных сообщений и из-за замыканий не должно быть никаких переписываний message, но мы передаем сообщение по указателю и, может, в другом месте кода кто-нибудь че-нибудь да перепишет

2024-12-04 16:06 UTC, Vanv1k commented on bot/handlers/collector.go
> +	processMessagesForUser(state, sender, message, 2*time.Second)
а может задержку вынести в константу? зачем ее передавать, если она одинаковая для всех

2024-12-04 16:06 UTC, Vanv1k commented on bot/handlers/event.go
> +}
вынести бы структуры вообще в отдельный пакет. мб models

2024-12-04 16:06 UTC, Vanv1k commented on bot/handlers/handlers.go
>  }
тоже вынес бы в отдельный пакет

2024-12-04 16:06 UTC, Vanv1k commented on bot/handlers/collector.go
> +		ctx := &UserEventContext{
ctx путает. userEventCtx, например, явно указывает, что это не стандартный context.Context, а наша структура.

2024-12-04 16:06 UTC, Vanv1k commented on bot/handlers/event.go
> +		body, _ := io.ReadAll(resp.Body)
почему игнорим ошибку? может же косячно прийти, почему бы не вывести ее тоже в лог

2024-12-04 16:06 UTC, Vanv1k commented on bot/handlers/event.go
> +func createEvent(ctx *UserEventContext) (*CalendarResponse, error) {
processEvent или handleEventCreation? две функции с create, но эта по сути обращается к другим, а не создает сама

2024-12-04 16:06 UTC, Vanv1k commented on bot/messages/messages.go
> +}
про мапу подумать надо

2024-12-04 16:06 UTC, Vanv1k commented on bot/messages/messages.go
> +}
надо че то придумать с пустым интерфейсом, мб дженерики, например та же 
type Message[T any] struct {
	Static  string
	Dynamic func(args T) string
}

или мб структурку можно будет придумать универсальную

2024-12-04 16:06 UTC, Vanv1k commented on bot/messages/messages.go
>  	}
беда)))

2024-12-04 16:08 UTC, Vanv1k commented on bot/handlers/handlers.go
>  }
мимо попал)
там тоже две структурки короче, из серии что нужно отправить по запросу, стоит вынести тож в пакет

2024-12-04 19:29 UTC, Azat-Bilalov commented on bot/handlers/collector.go
> +}
вынес как методы ProcessingState

2024-12-04 19:30 UTC, Azat-Bilalov commented on bot/handlers/collector.go
> +	}()
Сделал. Тут вопрос на подумать - можно ли передавать сообщение по ссылке? или оно будет затираться в ходе выполнения горутин?

2024-12-04 20:27 UTC, Azat-Bilalov commented on bot/messages/messages.go
> +}
Будем решать в рамках другой задачи (с добавлением шаблона и т.д.), здесь же пока давай оставим

2024-12-04 20:27 UTC, Azat-Bilalov commented on bot/messages/messages.go
>  	}
тоже в рамках другой задачи)

2024-12-04 20:31 UTC, Azat-Bilalov commented on bot/handlers/event.go
> +		body, _ := io.ReadAll(resp.Body)
надо в идеале сделать обёртку для запросов, чтобы было красивее и везде

2024-12-05 08:47 UTC, Vanv1k approved these changes

2024-12-05 08:47 UTC, Vanv1k commented on bot/handlers/collector.go
> +	message tgbotapi.Message,
передавать все же можно и по указателю))
просто внутрь горутины прокидываем копию

2024-12-05 08:47 UTC, Vanv1k commented on bot/handlers/event.go
> +		body, _ := io.ReadAll(resp.Body)
та же фигня с ошибкой

2024-12-05 08:48 UTC, Vanv1k commented on bot/handlers/collector.go
> +	}()
по ссылке можно, мы ж во внутрь горутины кинем копию и все

2024-12-05 08:52 UTC, merged